### ISSUE TITLE
Asking for documentation

### ISSUE THREAD

**Issue by kareemsuhail** [aws-samples/aws-appsync-chat#2]
Hello there!
I was looking for the documentation of these directives in schema.graphql 
@auth,@model
I didn't find any thing in Appsync documentation and AppSync API reference 
please can you provide full  documentation for how to use them

**Comment by palpatim** [comment]
@kareemsuhail 

You can find documentation on those directives [here](https://aws-amplify.github.io/docs/cli/graphql#directives)

**Comment by kareemsuhail** [comment]
thanks! I will close the issue
